models/Address.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 24.09.17
 * Time: 20:06
 */

namespace app\models;


use yii\db\ActiveRecord;

class Address extends ActiveRecord
{
	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'addresses';
	}
	
	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['index'], 'match','pattern'=>'/\d{5}/'],
			[['country'], 'match','pattern' => '/[A-Z]{2}/','message' => 'Country should contain 2 capitalized letters.'],
			[['city'],'string'],
			[['street'], 'string'],
			[['houseNumber'], 'string'],
			[['apartmentNumber'],'string']
		];
	}
	
	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'index'=>'Index',
			'indexString'=>'Index',
			'country'=>'Country',
			'city'=>'City',
			'street'=>'Street',
			'houseNumber'=>'House number',
			'apartmentNumber'=>'Apartment (office) number'
		];
	}
	
	public function getUser(){
		return $this->hasOne(User::className(),['id'=>'userId']);
	}
public function getIndexString(){
	return sprintf("%05d", $this->index);
}
}

models/User.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $login
 * @property string $firstName
 * @property string $lastName
 * @property int $gender
 * @property \DateTime $createdAt
 * @property string $email
 * @property string $authKey
 * @property string $password
 */
class User extends ActiveRecord
{
	const MALE = 0;
	const FEMALE = 1;
	const OTHER = 2;
	
	public $repeatPassword;
	
	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'users';
	}
	
	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['gender'], 'integer'],
			[['createdAt'], 'safe'],
			[['password','repeatPassword'],'required'],
			[['password'],'string','min'=>6,'max' => 255],
			[['login', 'firstName', 'lastName', 'email'], 'string', 'max' => 255],
			[['login'], 'unique','when' => function($model,$attribute){
			return $model->{$attribute}!==$model->getOldAttribute($attribute);
			}],
			[['email'], 'unique','when' => function($model,$attribute){
				return $model->{$attribute}!==$model->getOldAttribute($attribute);
			}],
			[['repeatPassword'],'compare','compareAttribute' => 'password','message' => 'Passwords are not equal.']
		];
	}
	
	public function scenarios()
	{
		return [
			'create'=>[
				'login',
				'password',
				'repeatPassword',
				'firstName',
				'lastName',
				'gender',
				'email'
			],
			'update'=>[
				'login',
				'password',
				'repeatPassword',
				'firstName',
				'lastName',
				'gender',
				'email'
			]
		];
	}
	
	
	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'login' => 'Login',
			'firstName' => 'First Name',
			'lastName' => 'Last Name',
			'gender' => 'Gender',
			'genderString' => 'Gender',
			'createdAt' => 'Created At',
			'email' => 'Email',
			'password' => 'Password',
		];
	}
	
	public function setGender($value)
	{
		$this->attributes['gender'] = $value;
	}
	
	
	public function getGenderString()
	{
		switch ($this->gender) {
			case self::MALE: {
				return 'male';
			}
			case self::FEMALE: {
				return 'female';
			}
			case self::OTHER: {
				return 'other';
			}
		}
	}
	
	public function getFullName()
	{
		return "$this->firstName $this->lastName";
	}
	
	public function getAddresses()
	{
		return $this->hasMany(Address::className(), ['userId' => 'id']);
	}
	
	public function beforeSave($insert)
	{
		$this->firstName=ucfirst($this->firstName);
		$this->lastName=ucfirst($this->lastName);
		return parent::beforeSave($insert);
	}
}

models/UserSearch.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 25.09.17
 * Time: 15:45
 */

namespace app\models;


use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;

class UserSearch extends Model
{
	public $login;
	public $firstName;
	public $lastName;
	public $email;
	public $gender;
	
	public function rules()
	{
		return [
			[['login','firstName','lastName','email'],'string'],
			[['gender'],'integer']
		];
	}
	
	
	public function search($filter)
	{
		$query=User::find();
		$dataProvider=new ActiveDataProvider([
			'query'=>$query,
			'pagination'=>new Pagination(['pageSize'=>10])
		]);
		if($this->load($filter)) {
			
			if ($this->login) {
				$query->andFilterWhere(['like', '{{users}}.login', $this->login]);
			}
			if($this->firstName){
				$query->andFilterWhere(['like','{{users}}.firstName',$this->firstName]);
			}
			if($this->lastName){
				$query->andFilterWhere(['like','{{users}}.lastName',$this->lastName]);
			}
			if($this->email){
				$query->andFilterWhere(['like','{{users}}.email',$this->email]);
			}
			if(isset($this->gender)){
				$query->andFilterWhere(['{{users}}.gender'=>$this->gender]);
			}
		}
		return $dataProvider;
	}
}

controllers/AddressesController.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 24.09.17
 * Time: 20:39
 */

namespace app\controllers;


use app\models\Address;
use app\models\User;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;

class AddressesController extends Controller
{
	public function actionEdit($id){
		$address=Address::findOne($id);
		if($address->load(Yii::$app->request->post()&&$address->validate())){
			$address->save();
			return $this->redirect(Url::toRoute(['user/details','id'=>$address->user->id]));
		}
		return $this->render('edit',['address'=>$address,'errors'=>$address->errors]);
	}
	
	public function actionCreate($userId){
		$address=new Address();
		$user=User::findOne($userId);
		if($address->load(Yii::$app->request->post())&&$address->validate()){
			$address->userId=$user->id;
			$address->save();
			return $this->redirect(Url::toRoute(['users/details','id'=>$userId]));
		}
		return $this->render('create', ['address' => $address,'user'=>$user]);
	}
	
	public function actionDelete($id){
		$address=Address::findOne($id);
		$user=$address->user;
		if(count($user->addresses)<2){
			Yii::$app->getSession()->setFlash('error',"User can't have less than 1 address.");
			return $this->redirect(Url::toRoute(['users/details','id'=>$user->id]));
		}
		if(Yii::$app->request->isPost){
			$address->delete();
			return $this->redirect(Url::toRoute(['users/details','id'=>$address->userId]));
		}
		return $this->render('delete');
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			]
		];
	}
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\Address;
use app\models\User;
use app\models\UserSearch;
use yii\data\ActiveDataProvider;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;

class UsersController extends Controller
{
	public function actionList()
	{
		$userSearchModel=new UserSearch();
		$filter=Yii::$app->request->get();
		$provider=$userSearchModel->search($filter);
		return $this->render('list', ['provider' => $provider,'filterModel'=>$userSearchModel]);
	}
	
	public function actionEdit($id)
	{
		$user = User::findOne($id);
		$user->setScenario('update');
		if ($user->load(Yii::$app->request->post()) && $user->validate()) {
			$user->save(false);
			return $this->redirect(Url::toRoute(['users/details', 'id' => $user->id]));
		}
		//print_r($user->errors);
		return $this->render('edit', ['user' => $user]);
	}
	
	public function actionDetails($id)
	{
		$user = User::findOne($id);
		$addressesProvider = new ActiveDataProvider([
			'query' => $user->getAddresses(),
			'pagination' => [
				'pageSize' => 5
			]
		]);
		return $this->render('details', ['user' => $user, 'addressesProvider' => $addressesProvider]);
	}
	
	public function actionCreate()
	{
		$user = new User();
		$user->setScenario('create');
		$address = new Address();
		$address->setScenario('create');
		if ($user->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post()) && $user->validate() && $address->validate()) {
			$user->password=Yii::$app->security->generatePasswordHash(Yii::$app->request->post('password'));
			$user->save(false);
			$address->userId = $user->id;
			$address->save(false);
			return $this->redirect(Url::toRoute(['users/details', 'id' => $user->id]));
		}
		return $this->render('create', ['user' => $user, 'address' => $address]);
	}
	
	public function actionDelete($id){
		$user=User::findOne($id);
		if(Yii::$app->request->isPost){
			foreach ($user->addresses as $address){
				$address->delete();
			}
			$user->delete();
			return $this->redirect(Url::toRoute(['users/list']));
		}
		return $this->render('delete', ['user' => $user]);
	}
}

views/addresses/create.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 25.09.17
 * Time: 7:19
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

$this->title = 'New address';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-lg-6 col-md-8 col-lg-offset-3 col-md-offset-2">
		<h2>New Address for <?= $user->fullName ?></h2>
		<? $form = ActiveForm::begin() ?>
		<?= $form->field($address, 'index')->textInput() ?>
		<?= $form->field($address, 'country')->textInput() ?>
		<?= $form->field($address, 'city')->textInput() ?>
		<?= $form->field($address, 'street')->textInput() ?>
		<?= $form->field($address, 'houseNumber')->textInput() ?>
		<?= $form->field($address, 'apartmentNumber')->textInput() ?>
		<?= Html::submitButton('Create', ['class' => 'btn btn-primary pull-right']) ?>
		<? ActiveForm::end() ?>
	</div>
</div>

views/addresses/delete.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 25.09.17
 * Time: 13:34
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

$this->title = 'Delete addresss';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="panel-title">Delete address</div>
	</div>
	<div class="panel-body">
		<? $form = ActiveForm::begin() ?>
		<div class="form-group">
			<h4>Are you sure you want to delete this address?</h4>
		</div>
		<div class="form-group">
			<?= Html::a('Cancel', Yii::$app->request->referrer, ['class' => 'btn btn-primary']) ?>
			<?= Html::submitButton('Delete', ['class' => 'btn btn-danger pull-right']) ?>
		</div>
		<? ActiveForm::end() ?>
	</div>
</div>

views/addresses/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 24.09.17
 * Time: 20:38
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

$this->title = 'Edit address';
$this->params['breadcrumbs'][] = $this->title;
?>
<? if ($errors) {
	print_r($errors);
} ?>
<div class="row">
	<div class="col-lg-6 col-md-8 col-lg-offset-3 col-md-offset-2">
		<h2>Edit address</h2>
		<? $form = ActiveForm::begin() ?>
		<?= $form->field($address, 'index')->textInput(['value' => $address->indexString]) ?>
		<?= $form->field($address, 'country')->textInput() ?>
		<?= $form->field($address, 'city')->textInput() ?>
		<?= $form->field($address, 'street')->textInput() ?>
		<?= $form->field($address, 'houseNumber')->textInput() ?>
		<?= $form->field($address, 'apartmentNumber')->textInput() ?>
		<?= Html::submitButton('Save', ['class' => 'btn btn-success pull-right']) ?>
		<? ActiveForm::end() ?>
	</div>
</div>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
	<?php
	NavBar::begin([
		'brandLabel' => Yii::$app->name,
		'brandUrl' => Yii::$app->homeUrl,
		'options' => [
			'class' => 'navbar-inverse navbar-fixed-top',
		],
	]);
	echo Nav::widget([
		'options' => ['class' => 'navbar-nav navbar-right'],
		'items' => [
			['label' => 'Users', 'url' => ['/users']]
		],
	]);
	NavBar::end();
	?>
	
	<div class="container">
		<?= Breadcrumbs::widget([
			'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		]) ?>
		<?= Alert::widget() ?>
		<?= $content ?>
	</div>
</div>

<footer class="footer">
	<div class="container">
		<p class="pull-left">&copy; Bintime <?= date('Y') ?></p>
		
		<p class="pull-right"><?= Yii::powered() ?></p>
	</div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/users/create.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 25.09.17
 * Time: 7:48
 */

use app\models\User;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

$this->title = 'New user';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-lg-6 col-md-8 col-lg-offset-3 col-md-offset-2">
		<? $form = ActiveForm::begin() ?>
		<div>
			<h2>New user</h2>
			<?= $form->field($user, 'login')->textInput() ?>
			<?= $form->field($user, 'password')->passwordInput() ?>
			<?= $form->field($user, 'repeatPassword')->passwordInput() ?>
			<?= $form->field($user, 'firstName')->textInput() ?>
			<?= $form->field($user, 'lastName')->textInput() ?>
			<?= $form->field($user, 'gender')->dropDownList([User::MALE => 'male', User::FEMALE => 'female', User::OTHER => 'other']) ?>
			<?= $form->field($user, 'email')->input('email') ?>
		
		</div>
		
		<div>
			<h3>User address</h3>
			<?= $form->field($address, 'index')->textInput() ?>
			<?= $form->field($address, 'country')->textInput() ?>
			<?= $form->field($address, 'city')->textInput() ?>
			<?= $form->field($address, 'street')->textInput() ?>
			<?= $form->field($address, 'houseNumber')->textInput() ?>
			<?= $form->field($address, 'apartmentNumber')->textInput() ?>
			<?= Html::submitButton('Create', ['class' => 'btn btn-success pull-right']) ?>
		</div>
		<? ActiveForm::end() ?>
	</div>
</div>

views/users/delete.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 25.09.17
 * Time: 13:08
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Alert;
use yii\bootstrap\Html;

$this->title = "Delete $user->fullName";
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="panel panel-default">
	<div class="panel-heading">
		<div class="panel-title">Delete <?= $user->fullName?></div>
	</div>
	<div class="panel-body">
		<?$form=ActiveForm::begin()?>
		<div class="form-group">
			<h4>Are you sure you want to delete <?= $user->fullName ?>?</h4>
		</div>
		<div class="form-group">
			<?=Html::a('Cancel',Yii::$app->request->referrer,['class'=>'btn btn-primary'])?>
		<?=Html::submitButton('Delete',['class'=>'btn btn-danger pull-right'])?>
		</div>
		<?ActiveForm::end()?>
	</div>
</div>

views/users/details.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 24.09.17
 * Time: 19:59
 */

use yii\bootstrap\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\DetailView;

$this->title = $user->fullName;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
	<h3><?= $user->fullName ?> detail info.</h3>
	<?= DetailView::widget([
		'model' => $user,
		'attributes' => [
			'id',
			'login',
			'firstName',
			'lastName',
			'genderString',
			'createdAt:datetime',
			'email'
		]
	]) ?>
	<?= Html::a('Edit user', Url::toRoute(['users/edit', 'id' => $user->id]), ['class' => 'btn btn-primary pull-right']) ?>
</div>
<div class="container">
	<h4>Addresses</h4>
	<?= GridView::widget([
		'dataProvider' => $addressesProvider,
		'columns' => [
			[
				'attribute' => 'index',
				'value'=>'indexString'
			],
			'country',
			'city',
			'street',
			'houseNumber',
			'apartmentNumber',
			[
				'label' => 'Actions',
				'content' => function ($address) {
					return '<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li>' . Html::a("Edit", Url::toRoute(["addresses/edit", "id" => $address->id])) . '</li>
    <li>' . Html::a("Delete", Url::toRoute(["addresses/delete", "id" => $address->id])) . '</li>
  </ul>
</div>';
				}
			]
		]
	]) ?>
	<?= Html::a('New address', Url::toRoute(['addresses/create', 'userId' => $user->id]), ['class' => 'btn btn-primary pull-right']) ?>
</div>

views/users/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 24.09.17
 * Time: 11:39
 */

use app\models\User;
use yii\bootstrap\ActiveForm;
$this->title = "Edit $user->fullName";
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-lg-6 col-md-8 col-lg-offset-3 col-md-offset-2">
<h2>Edit <?=$user->login?></h2>
<? $form=ActiveForm::begin()?>
<?=$form->field($user,'login')->textInput()?>
<?=$form->field($user,'password')->passwordInput(['value'=>''])?>
<?=$form->field($user,'repeatPassword')->passwordInput()?>
<?=$form->field($user,'firstName')->textInput()?>
<?=$form->field($user,'lastName')->textInput()?>
<?=$form->field($user,'gender')->dropDownList([User::MALE=>'male',User::FEMALE=>'female',User::OTHER=>'other'])?>
<?=$form->field($user,'email')->textInput()?>
<?= \yii\bootstrap\Html::submitButton('Save',['class'=>'btn btn-success pull-right'])?>
<? ActiveForm::end() ?>
	</div>
</div>

views/users/list.php
<?php
/**
 * Created by PhpStorm.
 * User: marievych
 * Date: 24.09.17
 * Time: 9:11
 */

use app\models\User;
use yii\grid\DataColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
	<?= GridView::widget([
		'filterModel' => $filterModel,
		'dataProvider' => $provider,
		'columns' => [
			[
				'attribute' => 'login',
				'content' => function ($user) {
					return Html::a($user->login, Url::toRoute(['users/details', 'id' => $user->id]));
				}
			],
			'firstName',
			'lastName',
			'email',
			[
				'attribute' => 'gender',
				'class' => DataColumn::className(),
				'value' => function ($user) {
					return $user->genderString;
				},
				'filter' => [User::MALE => 'male', User::FEMALE => 'female', User::OTHER => 'other']
			],
			'createdAt:datetime',
			[
				'label' => 'Actions',
				'format' => 'html',
				'content' => function ($user) {
					return '<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li>' . Html::a("Edit", Url::toRoute(["users/edit", "id" => $user->id])) . '</li>
    <li>' . Html::a("Delete", Url::toRoute(["users/delete", "id" => $user->id])) . '</li>
  </ul>
</div>';
				}
			]
		]
	
	]) ?>
	<?= Html::a('New user', Url::toRoute(['users/create']), ['class' => 'btn btn-primary pull-right']) ?>